name: CI/CD for GovData-Dashboard

on:
   push:
     branches:
       - main

jobs:
  ci_cd:
    name: CI/CD
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Build Docker Container
        run: nix build .\#docker-image

      - name: Load Docker Container
        run: docker image load -i result

      - name: Log in to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Upload to ghcr.io
        run: docker push ghcr.io/rschardt/govdata-dashboard:latest
